### ISSUE TITLE
Reproducing paper results fails 

### ISSUE THREAD

**Issue by andreaschari** [nusnlp/esc#1]
Trying to reproduce the paper results crashes the script.
Running:` export EXP_DIR=conll-exp `
and then: `python run.py --test --data_dir $EXP_DIR/test-text --m2_dir $EXP_DIR/test-m2 --model_path $EXP_DIR/models/paper_model.pt --vocab_path $EXP_DIR/paper_vocab.idx --output_path $EXP_DIR/outputs/test.out`

yields the following error:

```
Traceback (most recent call last):
  File "run.py", line 542, in <module>
    main(args)
  File "run.py", line 516, in main
    with open(args.output_path, 'w', encoding='utf-8') as out:
FileNotFoundError: [Errno 2] No such file or directory: 'conll-exp/outputs/test.out'
```
reproducing the bea-2019 experiments and re-training works fine.

**Comment by mrqorib** [comment]
Hi @andreaschari,
I believe you just need to create the `outputs` folder inside the `conll-exp` directory.

**Comment by andreaschari** [comment]
yup, that was issue now, The scripts work fine now!
