### ISSUE TITLE
Usage for different languages

### ISSUE THREAD

**Issue by 14kwonss** [nusnlp/esc#3]
Hi im trying to use this github repo to evaluate GEC tasks on other languages other than English. I have the (.m2) files but some languages dont have tools like ERRANT. In that case is it still possible to run the ensemble method? if so what are the necessary files?

Thank you!!

**Comment by mrqorib** [comment]
Hi @14kwonss, thank you for your interest in this work. ERRANT is needed to parse the data into M2 format. if you have the M2 files for all training and testing data, you don't need ERRANT. However, that means you need to annotate the edit type for each of the base system's output.

The files you need are:
- Base models' raw output text for training (inside the dev-text folder)
- Base models' outputs in m2 format for training (inside the dev-m2 folder)
- Base models' raw output for testing (inside the test-text folder)
- Base models' outputs in m2 format for testing (inside the test-m2 folder)

Make sure you use the same basename for all files. For example, if you are combining system A, B, and C, the files in the *-text folder should be named A.txt, B.txt, C.txt and the files in the *-m2 folder should be named A.m2, B.m2, C.m2. After all the files are organized in the correct folders, you can follow the command in the README.
